### ISSUE TITLE
Error in running SQL magic

### ISSUE THREAD

**Issue by devender-yadav** [jupyter-incubator/sparkmagic#529] opened 2019-05-15 11:40 UTC
Trying to run SQL query using **%%SQL** magic

    %%sql 
    select USR_ID from table limit 5

> Error:
Cannot parse object as JSON: '['b\'{"USR_ID":8694440}\'', 'b\'{"USR_ID":8694440}\'', 'b\'{"USR_ID":8694440}\'', 'b\'{"USR_ID":8694440}\'', 'b\'{"USR_ID":8694440}\'']'

**Comment by juliusvonkohout** [comment] 2019-05-16 16:23
Well i have the same problem and created two patches. This repository seems abandoned.
These are the updated dependencies

          'hdijupyterutils>=0.6',
          'autovizwidget>=0.6',
          'ipython>=4.0.2,<8',
          'nose',
          'mock',
          'pandas>=0.17.1',
          'numpy',
          'requests',
          'ipykernel>=4.2.2,<6',
          'ipywidgets>5.0.0,<8.0',
          'notebook>=4.2,<6.0',
          'tornado>=4',
          'requests_kerberos>=0.8.0'

and i applied to patches.
in sparkstorecommand.py 
    def _pyspark_command(self, spark_context_variable_name, encode_result=False):
in sqlquery.py
    def _pyspark_command(self, sql_context_variable_name, encode_result=False):

pull request #528 

Furthermore i patched autovizwidget to allow plotly 3.9 
          'plotly>=1.10.0,<4.0',
          'ipywidgets>5.0.0,<8.0',
          'hdijupyterutils>=0.6',
          'notebook>=4.2,<6.0',
          'pandas>=0.20.1'

and hdijupyterutils

          'ipython>=4.0.2,<8',
          'nose',
          'mock',
          'ipywidgets>5.0.0',
          'ipykernel>=4.2.2,<6',
          'jupyter>=1,<2',
          'pandas>=0.17.1',
          'numpy',
          'notebook>=4.2'

We are using this with livy 0.4 and livy 0.5 but the maintainer of the repository seems to be gone. Maybe it is time to fork and name it sparkmagic2

[hdijupyterutils-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188034/hdijupyterutils-0.12.7.tar.gz)
[autovizwidget-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188035/autovizwidget-0.12.7.tar.gz)
[sparkmagic-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188036/sparkmagic-0.12.7.tar.gz)

**Comment by juliusvonkohout** [comment] 2019-05-16 19:44
pandas==0.22.*
hdfs==2.1.*

autovizwidget-0.12.7.tar.gz
hdijupyterutils-0.12.7.tar.gz
sparkmagic-0.12.7.tar.gz

# Sparkmagic upstream is dead so we use prebuilt packages
#These are the updated dependencies for sparkmagic
#
#      'hdijupyterutils>=0.6',
#      'autovizwidget>=0.6',
#      'ipython>=4.0.2,<8',
#      'nose',
#      'mock',
#      'pandas>=0.17.1',
#      'numpy',
#      'requests',
#      'ipykernel>=4.2.2,<5',
#      'ipywidgets>5.0.0,<8.0',
#      'notebook>=4.2,<6.0',
#      'tornado>=4',
#      'requests_kerberos>=0.8.0'###
#
#and i applied 2 patches:
#  pip install -r /tmp/src/kernel/Sparkmagic/requirements.txt
#  # Patch Spargmagic for bug https://github.com/jupyter-incubator/sparkmagic/issues/357
#  patch -i /tmp/src/kernel/Sparkmagic/patch1 $(pip show sparkmagic | grep Location | \
#    cut -d" " -f2)/sparkmagic/livyclientlib/sparkstorecommand.py
#  patch -i /tmp/src/kernel/Sparkmagic/patch2 $(pip show sparkmagic | grep Location | \
#    cut -d" " -f2)/sparkmagic/livyclientlib/sqlquery.py
#
#in sparkstorecommand.py
#def _pyspark_command(self, spark_context_variable_name, encode_result=False):
#in sqlquery.py
#def _pyspark_command(self, sql_context_variable_name, encode_result=False):
#
#pull request #528
#
#Furthermore i patched autovizwidget to allow plotly 3.9
#
#      'plotly>=1.10.0,<4.0',
#      'ipywidgets>5.0.0,<8.0',
#      'hdijupyterutils>=0.6',
#      'notebook>=4.2,<6.0',
#      'pandas>=0.20.1'
#
#and hdijupyterutils
#
#      'ipython>=4.0.2,<8',
#      'nose',
#      'mock',
#      'ipywidgets>5.0.0',
#      'ipykernel>=4.2.2,<5',
#      'jupyter>=1,<2',
#      'pandas>=0.17.1',
#      'numpy',
#      'notebook>=4.2'
#
#We are using this with livy 0.4 and livy 0.5 but the maintainer of the repository seems to be gone. Maybe it is time to fork and rename it to sparkmagic2...
[hdijupyterutils-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188756/hdijupyterutils-0.12.7.tar.gz)
[autovizwidget-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188757/autovizwidget-0.12.7.tar.gz)
[sparkmagic-0.12.7.tar.gz](https://github.com/jupyter-incubator/sparkmagic/files/3188758/sparkmagic-0.12.7.tar.gz)

**Comment by ashkan-leo** [comment] 2019-05-23 14:44
I also get `cannot parse object as JSON` exception when running a sql query.

**Comment by juliusvonkohout** [comment] 2019-05-23 15:46
> I also get `cannot parse object as JSON` exception when running a sql query.

Try this https://pypi.org/project/sparkmagic3/

**Comment by juliusvonkohout** [comment] 2019-06-25 09:32
@itamarst duplicate of #544 #538 please close

**Comment by itamarst** [comment] 2019-06-25 17:46
Fixed by #540.

**Closed by itamarst** 2019-06-25 17:46 UTC
