### ISSUE TITLE
[BUG] Pandas 1.5.0 has breaking changes.

### ISSUE THREAD

**Issue by GaspardBT** [jupyter-incubator/sparkmagic#776] opened 2022-09-26 12:36 UTC
**Describe the bug**
Import Sparkmagic fail with `ImportError: cannot import name 'DataError' from 'pandas.core.groupby'

**To Reproduce**
Run the Contributing [steps](https://github.com/jupyter-incubator/sparkmagic#contributing) with `python3.9.7`
Then run the tests: `nosetests hdijupyterutils autovizwidget sparkmagic`
The tests fails with: `ImportError: cannot import name 'DataError' from 'pandas.core.groupby'`

**Expected behavior**
The tests should succeed 

**Additional context**
Pandas released a new [version](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#what-s-new-in-1-5-0-september-19-2022) with what can be seen as breaking changes as they change the path for [errors](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#what-s-new-in-1-5-0-september-19-2022:~:text=(GH47003)-,DataError,-%2C%20SpecificationError%2C) used in sparkmagics [here](https://github.com/jupyter-incubator/sparkmagic/search?q=dataerror)
This can be solved by either changing the `requirements.txt` to limit pandas version under `1.5.0` or to change the import path to the new ones.
I created a [PR](https://github.com/jupyter-incubator/sparkmagic/pull/775) that implemented the second solutions.

**Comment by amansinghvi41** [comment] 2022-10-13 14:18
I am facing the same issue. After upgrading to pandas 1.5.0 sparkmagic is breaking. Any WA for now until this is fixed ?

**Comment by sergiimk** [comment] 2022-11-18 00:07
Also encountered this.

The cause of this isn't really a "breaking change in Pandas" but rather Sparkmagic reaching into Pandas' internal paths to import `DataError` type.

If you look at the Panda's [API reference](https://pandas.pydata.org/docs/dev/reference/api/pandas.errors.DataError.html) - the correct/public import path is:
```python
from pandas.errors import DataError
```

In our docker image we added a following temporary workaround which solved the issue:
```
sed -i 's/from pandas.core.groupby import DataError/from pandas.errors import DataError/g' /opt/conda/lib/python3.10/site-packages/autovizwidget/plotlygraphs/graphbase.py
sed -i 's/from pandas.core.groupby import DataError/from pandas.errors import DataError/g' /opt/conda/lib/python3.10/site-packages/autovizwidget/plotlygraphs/piegraph.py
```

**Comment by iirekm-test** [comment] 2022-12-27 08:46
+1, either running locally, or docker build and then docker run, I get the error. Sparkmagic currently (2022) is useless until some fix is done.

**Comment by devstein** [comment] 2022-12-30 02:00
This has been fixed in the [latest release](https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.20.1). 

Thank you all for your patience and thank you @GaspardBT for the patch!

**Closed by devstein** 2022-12-30 02:00 UTC
