### ISSUE TITLE
[BUG] Ipython API change

### ISSUE THREAD

**Issue by spencer-bullent-work** [jupyter-incubator/sparkmagic#749] opened 2022-02-17 17:48 UTC
**Describe the bug**
Starting a new session on IPython 8.0.1 produces the error: `AttributeError: 'ZMQInteractiveShell' object has no attribute 'write'`

**To Reproduce**
Start a session with the following versions:
IPython==8.0.1
sparkmagic==0.19.1

**Expected behavior**
Session should start

**Screenshots**
N/A

**Versions:**
 - SparkMagic - 0.19.1
 - Livy (if you know it)
 - Spark

**Additional context**
On downgrading IPython to 7.31.1 session successfully starts.

**Comment by juliusvonkohout** [comment] 2022-03-15 10:02
This project seems to be abandoned. I also encounter the same issue.

**Comment by itamarst** [comment] 2022-03-15 11:28
@juliusvonkohout please be kind, the project is currently being maintained by volunteers, presumably with limited time.

**Comment by devstein** [comment] 2022-04-26 22:52
Duplicate of #747

**Comment by devstein** [comment] 2022-04-26 22:53
A workaround has been released in `0.19.2`

**Closed** 2022-12-31 16:29 UTC
