### ISSUE TITLE
%%sql Select 1,2,3 not working for scala interpreter

### ISSUE THREAD

**Issue by Reimus** [jupyter-incubator/sparkmagic#445] opened 2018-03-23 23:12 UTC
From fresh pip installation following instructions on Debian 9:

Test:

%%sql
select 1,2,3

For Python2 interpreter it works, but for Scala it does not.
Error is:
Cannot parse object as JSON: '[u'{"1":1,"2":2,"3":3}', u'']'

**Comment by nasheqlbrm** [comment] 2018-07-25 15:51
I ran into the same issue while using the Spark kernel from Jupyter. 

The error is due to the last entry in the array seen in the error message. This array entry is, in turn, caused by a trailing newline in the result text from the query. 

A possible fix for this could be to change [Line 56](https://github.com/jupyter-incubator/sparkmagic/blob/634ee0d356b8e9685fe006739b7543149cfef374/sparkmagic/sparkmagic/utils/utils.py#L56) of the records_to_dataframe method in sparkmagic/sparkmagic/sparkmagic/utils/utils.py to: 

`strings = records_text.rstrip('\n').split('\n') `

where the rstrip gets rid of the trailing newline.

However this may not be the right workaround. It is likely better to determine how the trailing new line character enters the records_text and then go from there.

For reference,
%%info
Current session configs: {'driverMemory': '18000M', 'executorCores': 5, 'kind': 'spark'}

**Comment by mhuang74** [comment] 2019-04-08 16:10
As commented on #471 :

Filtering out empty string elements from array after *split* in [utils.records_to_dataframe](https://github.com/jupyter-incubator/sparkmagic/blob/634ee0d356b8e9685fe006739b7543149cfef374/sparkmagic/sparkmagic/utils/utils.py#L56) seems to have fixed the problem for me:

```
def records_to_dataframe(records_text, kind, coerce=None):
    if records_text in ['', '[]']:
        strings = []
    else:
        strings = records_text.split('\n')
        # fix https://github.com/jupyter-incubator/sparkmagic/issues/471 by removing empty string elements from array
        strings = filter(None, strings)
    try:
        data_array = [json.JSONDecoder(object_pairs_hook=OrderedDict).decode(s) for s in strings]
```

**Comment by alexmnyc** [comment] 2019-05-23 18:54
same here

**Comment by itamarst** [comment] 2019-07-12 17:40
I am having trouble reproducing this. Do you still have this problem?

**Comment by itamarst** [comment] 2019-07-12 17:41
The code now has a `.strip()` which should strip leading/ending newlines, which probably explains why I can't reproduce this. So going to say it's fixed. Please re-open if you're still having issues.

**Closed by itamarst** 2019-07-12 17:41 UTC
