### ISSUE TITLE
Pandas dataframe of 1 million rows hangs

### ISSUE THREAD

**Issue by rahulsingh303** [jupyter-incubator/sparkmagic#364] opened 2017-06-07 16:42 UTC
Hi,

We want 1 million rows to be read from our hive parquet table into Pandas data frame , the table has over 30 million rows , but to get started we need 1 million rows . Code works fine for small set (thousands) of data , but hangs for million rows . There are only 8 columns in table . I am using below configuration and code:

%%spark -c sql -o df_hvac --quiet -n 1000000
select * from buy_click_p limit 1000000

Session properties:
{"executorCores": 2, "driverMemory": "5g"}

Also I see application runs in local mode always , even though I have set in livy.conf livy.spark.master = yarn-cluster.

Please help and let me know if I need to provide any more information.

-Rahul

**Comment by aggFTW** [comment] 2017-06-07 16:48
I can help figure out what's going on from Jupyter/sparkmagic's point of view. When you say it hangs, what is Spark actually doing? What's the status of the statement being executed according to Livy?

Tuning your Spark application for number of executor cores, driver memory, and other properties is out of the scope of this project and I cannot help you on that.

When you say that the application runs in local mode, you mean that Spark reports the master as being local? It seems like something is not set up properly on Livy. I would suggest asking for help in the Livy forums as to what may be the config problem.

**Comment by rahulsingh303** [comment] 2017-06-07 17:41
Thanks for quick response !

What I see in spark UI that all tasks get completed , here are some of final line in livy terminal logs :+1: 


17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 3.0, whose tasks have all completed, from pool
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: ShuffleMapStage 3 (toJSON at NativeMethodAccessorImpl.java:-2) finished in 66.511 s
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: looking for newly runnable stages
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: running: Set()
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: waiting: Set(ResultStage 4)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: failed: Set()
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: Submitting ResultStage 4 (PythonRDD[16] at RDD at PythonRDD.scala:43), which has no missing parents
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.MemoryStore: Block broadcast_6 stored as values in memory (estimated size 10.6 KB, free 396.7 KB)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 6.0 KB, free 402.7 KB)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.BlockManagerInfo: Added broadcast_6_piece0 in memory on localhost:22738 (size: 6.0 KB, free: 2.6 GB)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO spark.SparkContext: Created broadcast 6 from broadcast at DAGScheduler.scala:1006
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 4 (PythonRDD[16] at RDD at PythonRDD.scala:43)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.TaskSchedulerImpl: Adding task set 4.0 with 1 tasks
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 4.0 (TID 408, localhost, executor driver, partition 0,NODE_LOCAL, 2307 bytes)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO executor.Executor: Running task 0.0 in stage 4.0 (TID 408)
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.ShuffleBlockFetcherIterator: Getting 203 non-empty blocks out of 203 blocks
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 1 ms
17/06/07 11:58:33 INFO ContextLauncher: 17/06/07 11:58:33 INFO storage.BlockManagerInfo: Removed broadcast_5_piece0 on localhost:22738 in memory (size: 4.2 KB, free: 2.6 GB)
17/06/07 11:58:39 INFO ContextLauncher: 17/06/07 11:58:39 INFO python.PythonRunner: Times: total = 5832, boot = 5, init = 6, finish = 5821
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO storage.MemoryStore: Block taskresult_408 stored as bytes in memory (estimated size 164.7 MB, free 165.1 MB)
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO storage.BlockManagerInfo: Added taskresult_408 in memory on localhost:22738 (size: 164.7 MB, free: 2.4 GB)
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO executor.Executor: Finished task 0.0 in stage 4.0 (TID 408). 172692978 bytes result sent via BlockManager)
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO storage.BlockManagerInfo: Removed taskresult_408 on localhost:22738 in memory (size: 164.7 MB, free: 2.6 GB)
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 4.0 (TID 408) in 6872 ms on localhost (executor driver) (1/1)
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO scheduler.DAGScheduler: ResultStage 4 (runJob at PythonRDD.scala:393) finished in 6.917 s
17/06/07 11:58:40 INFO ContextLauncher: 17/06/07 11:58:40 INFO scheduler.DAGScheduler: Job 2 finished: runJob at PythonRDD.scala:393, took 73.751981 s
17/06/07 11:58:49 INFO ContextLauncher: 17/06/07 11:58:49 INFO storage.BlockManagerInfo: Removed broadcast_6_piece0 on localhost:22738 in memory (size: 6.0 KB, free: 2.6 GB)
17/06/07 11:59:04 INFO ContextLauncher: 17/06/07 11:59:04 INFO spark.ContextCleaner: Cleaned accumulator 6
17/06/07 11:59:04 INFO ContextLauncher: 17/06/07 11:59:04 INFO spark.ContextCleaner: Cleaned accumulator 5
17/06/07 11:59:04 INFO ContextLauncher: 17/06/07 11:59:04 INFO spark.ContextCleaner: Cleaned accumulator 4
17/06/07 11:59:04 INFO ContextLauncher: 17/06/07 11:59:04 INFO storage.BlockManagerInfo: Removed broadcast_2_piece0 on localhost:22738 in memory (size: 4.2 KB, free: 2.6 GB)
17/06/07 11:59:04 INFO ContextLauncher: 17/06/07 11:59:04 INFO spark.ContextCleaner: Cleaned accumulator 3


Then the cell in jupyter just remains active , I waited for 30 mins then I had to kill the Jupyter kerenel.
Thus I guess somewhere when Spark fetches all data and when sparkmagic tries to convert that to Pandas , it hangs and I have no clue where to see what it is trying to do in the backend as Spark UI has finished.

-Rahul

**Comment by aggFTW** [comment] 2017-06-07 20:51
What is the status of the livy statement? Go to /sessions/ID/statements/ID and check if the statement finished. If it did, then it might just be a case of volume and sparkmagic not being able to handle it. If you download the result of that statement to a text file, what is the size of the file?

To be honest, 1 million rows in a pandas dataframe sounds like a bad idea, and you probably want to reduce them to less rows to do anything meaningful with the dataframe. What is your use case?

**Comment by aggFTW** [comment] 2017-06-27 18:48
Closing due to silence after 3 weeks. We can re-open if needed.

**Closed by aggFTW** 2017-06-27 18:48 UTC

**Comment by veseliy** [comment] 2018-05-16 15:39
Hi, i have the same situation, can u help me to handle it?

**Comment by MochizukiShinichi** [comment] 2020-12-12 16:54
Hi, I’m also having this situation. What is the root cause of this issue?
