### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by yugam1** [jupyter-incubator/sparkmagic#384] opened 2017-07-12 09:34 UTC
Error appears anytime I run any code in any of kernels 
![image](https://user-images.githubusercontent.com/20748662/28110540-5c2354e4-6710-11e7-93a2-a7c991210fe1.png)

**Comment by aggFTW** [comment] 2017-07-12 18:47
It seems like your configuration for a livy endpoint is not valid. What does your config.json file look like?

**Comment by yugam1** [comment] 2017-07-13 05:05
It is like this:
{
  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "url": "http://localhost:8998",
    "auth": "None"
  },

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "url": "http://localhost:8998",
    "auth": "None"
  },
  "kernel_r_credentials": {
    "username": "",
    "password": "",
    "url": "http://localhost:8998"
  },

  "logging_config": {
    "version": 1,
    "formatters": {
      "magicsFormatter": { 
        "format": "%(asctime)s\t%(levelname)s\t%(message)s",
        "datefmt": ""
      }
    },
    "handlers": {
      "magicsHandler": { 
        "class": "hdijupyterutils.filehandler.MagicsFileHandler",
        "formatter": "magicsFormatter",
        "home_path": "~/.sparkmagic"
      }
    },
    "loggers": {
      "magicsLogger": { 
        "handlers": ["magicsHandler"],
        "level": "DEBUG",
        "propagate": 0
      }
    }
  },

  "wait_for_idle_timeout_seconds": 15,
  "livy_session_startup_timeout_seconds": 60,

  "fatal_error_suggestion": "The code failed because of a fatal error:\n\t{}.\n\nSome things to try:\na) Make sure Spark has enough available resources for Jupyter to create a Spark context.\nb) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.\nc) Restart the kernel.",

  "ignore_ssl_errors": false,

  "session_configs": {
    "driverMemory": "1000M",
    "executorCores": 2
  },

  "use_auto_viz": true,
  "coerce_dataframe": true,
  "max_results_sql": 2500,
  "pyspark_dataframe_encoding": "utf-8",
  
  "heartbeat_refresh_seconds": 30,
  "livy_server_heartbeat_timeout_seconds": 0,
  "heartbeat_retry_seconds": 10,

  "server_extension_default_kernel_name": "pysparkkernel",
  "custom_headers": {},
  
  "retry_policy": "configurable",
  "retry_seconds_to_sleep_list": [0.2, 0.5, 1, 3, 5],
  "configurable_retry_policy_max_retries": 8
}

**Comment by aggFTW** [comment] 2017-07-13 05:24
And you have livy running on http://localhost:8998/? Can you get a sessions response if you go to http://localhost:8998/sessions?

**Comment by jmeidam** [comment] 2017-07-18 08:44
I am also curious to find the answer to this issue. I am experiencing the same error and I have the same configuration file.

I can go to http://localhost:8998/sessions without authentication. I see a JSON tab opened which has the following info:
`{"from":0,"total":0,"sessions":[]}`

So no sessions, that might be bad. I can also add that I did not change anything in the docker files or config files, everything is as it is in the github repository (yesterday).
Furthermore, when doing `docker-compose up`, I see the following output, that may have some clues:

```Creating network "sparkmagicclone_default" with the default driver
Creating sparkmagicclone_spark_1 ...
Creating sparkmagicclone_spark_1 ... done
Creating sparkmagicclone_jupyter_1 ...
Creating sparkmagicclone_jupyter_1 ... done
Attaching to sparkmagicclone_spark_1, sparkmagicclone_jupyter_1
jupyter_1  | [W 08:10:55.921 NotebookApp] Unrecognized JSON config file version, assuming version 1
jupyter_1  | [I 08:10:55.935 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_1  | [W 08:10:55.972 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
jupyter_1  | [W 08:10:55.973 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
jupyter_1  | [I 08:10:56.340 NotebookApp] sparkmagic extension enabled!
jupyter_1  | [I 08:10:56.343 NotebookApp] Serving notebooks from local directory: /home/jovyan/work
jupyter_1  | [I 08:10:56.343 NotebookApp] 0 active kernels
jupyter_1  | [I 08:10:56.343 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
jupyter_1  | [I 08:10:56.343 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
spark_1    | 17/07/18 08:10:57 INFO StateStore$: Using BlackholeStateStore for recovery.
spark_1    | 17/07/18 08:10:57 INFO BatchSessionManager: Recovered 0 batch sessions. Next session id: 0
spark_1    | 17/07/18 08:10:57 INFO InteractiveSessionManager: Recovered 0 interactive sessions. Next session id: 0
spark_1    | 17/07/18 08:10:57 INFO InteractiveSessionManager: Heartbeat watchdog thread started.
spark_1    | 17/07/18 08:10:57 INFO WebServer: Starting server on http://spark:8998```

**Comment by aggFTW** [comment] 2017-07-18 20:25
:S? Docker images should work. Those logs and that payload look fine. No sessions are expected, as sessions should be created by the kernel.

Building and running the Docker images from master, I get this:

![image](https://user-images.githubusercontent.com/654204/28337919-f78d1870-6bbb-11e7-828a-663ae73032d4.png)

Can you run `%%info` on the kernels and post the result?

**Comment by jmeidam** [comment] 2017-07-19 08:41
When running that in either of the pyspark kernels I get:

```
Current session configs: {'kind': 'pyspark3'}
An internal error was encountered.
Please file an issue at https://github.com/jupyter-incubator/sparkmagic
Error:
'>=' not supported between instances of 'NoneType' and 'int'

There is one thing that I did different from the installation procedure described in the readme. In stead of first doing `docker-compose build`, I just did `docker-compose up` right away. It did seem to install everything, but could it be that some part of the setup is missing because I skipped that step?

**Comment by aggFTW** [comment] 2017-07-19 08:50
Please make sure you have the latest code and that you follow the instructions. It seems like you are hitting an exception that was fixed in the latest code. What do you get if you run:

```
%%bash
pip show sparkmagic
```

Do you get version `0.12.2`?

**Comment by jmeidam** [comment] 2017-07-19 09:31
Oh, I seem to have gotten an older version:

```
Name: sparkmagic
Version: 0.11.2
Summary: SparkMagic: Spark execution via Livy
Home-page: https://github.com/jupyter-incubator/sparkmagic/sparkmagic
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD 3-clause
Location: /Users/jmeidam/anaconda3/lib/python3.6/site-packages
Requires: hdijupyterutils, autovizwidget, mock, nose, requests, pandas, ipython, ipykernel, ipywidgets, tornado, numpy, notebook
```

I'm not sure how that happened, I cloned the git repo this Monday I think. I'll try pulling and rebuilding. I'll let you know what happens.

**Comment by jmeidam** [comment] 2017-07-19 10:14
Well, odd things were happening. I did a `git pull`, which said everything was up to date. 
I also noticed in the above output that sparkmagic was referring to an installation outside of the container. It may indeed have had something to do with me skipping the docker-compose _build_ step.
I removed everything, did a new `git clone`, then `docker-compose build` and `docker-compose up`. Now it works.

Thanks very much for your help.

These are outputs of the various commands suggested in this thread:

```
%%info
Current session configs: {'driverMemory': '1000M', 'kind': 'pyspark3', 'executorCores': 2}
No active sessions.
```

```
%%bash
pip show sparkmagic

---
Metadata-Version: 2.0
Name: sparkmagic
Version: 0.12.1
Summary: SparkMagic: Spark execution via Livy
Home-page: https://github.com/jupyter-incubator/sparkmagic/sparkmagic
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
Installer: pip
License: BSD 3-clause
Location: /opt/conda/lib/python3.5/site-packages
Requires: notebook, autovizwidget, pandas, hdijupyterutils, requests, ipykernel, ipython, nose, mock, numpy, tornado, requests-kerberos, ipywidgets
Classifiers:
  Development Status :: 4 - Beta
  Environment :: Console
  Intended Audience :: Science/Research
  License :: OSI Approved :: BSD License
  Natural Language :: English
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

```
%%bash
cat ~/.sparkmagic/config.json

{
  "kernel_python_credentials" : {
    "username": "",
    "password": "",
    "url": "http://spark:8998",
    "auth": "None"
  },

  "kernel_scala_credentials" : {
    "username": "",
    "password": "",
    "url": "http://spark:8998",
    "auth": "None"
  },
  "kernel_r_credentials": {
    "username": "",
    "password": "",
    "url": "http://spark:8998"
  },

  "logging_config": {
    "version": 1,
    "formatters": {
      "magicsFormatter": { 
        "format": "%(asctime)s\t%(levelname)s\t%(message)s",
        "datefmt": ""
      }
    },
    "handlers": {
      "magicsHandler": { 
        "class": "hdijupyterutils.filehandler.MagicsFileHandler",
        "formatter": "magicsFormatter",
        "home_path": "~/.sparkmagic"
      }
    },
    "loggers": {
      "magicsLogger": { 
        "handlers": ["magicsHandler"],
        "level": "DEBUG",
        "propagate": 0
      }
    }
  },

  "wait_for_idle_timeout_seconds": 15,
  "livy_session_startup_timeout_seconds": 60,

  "fatal_error_suggestion": "The code failed because of a fatal error:\n\t{}.\n\nSome things to try:\na) Make sure Spark has enough available resources for Jupyter to create a Spark context.\nb) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.\nc) Restart the kernel.",

  "ignore_ssl_errors": false,

  "session_configs": {
    "driverMemory": "1000M",
    "executorCores": 2
  },

  "use_auto_viz": true,
  "coerce_dataframe": true,
  "max_results_sql": 2500,
  "pyspark_dataframe_encoding": "utf-8",
  
  "heartbeat_refresh_seconds": 30,
  "livy_server_heartbeat_timeout_seconds": 0,
  "heartbeat_retry_seconds": 10,

  "server_extension_default_kernel_name": "pysparkkernel",
  "custom_headers": {},
  
  "retry_policy": "configurable",
  "retry_seconds_to_sleep_list": [0.2, 0.5, 1, 3, 5],
  "configurable_retry_policy_max_retries": 8
}
```

**Comment by jmeidam** [comment] 2017-07-19 11:53
Ok, it seems I am not quite out of the woods yet. I wanted to follow along the Ipython example of this repository (examples/Magics in IPython Kernel.ipynb), but I get the following error:

```
%load_ext sparkmagic.magics
---------------------------------------------------------------------------
BadUserConfigurationException             Traceback (most recent call last)
<ipython-input-2-784c1b92a201> in <module>()
----> 1 get_ipython().magic('load_ext sparkmagic.magics')

[...]

/opt/conda/lib/python3.5/site-packages/sparkmagic/controllerwidget/magicscontrollerwidget.py in _get_default_endpoints()
     36                     auth=endpoint_config.get("auth", None),
     37                     url=endpoint_config["url"],
---> 38                     implicitly_added=True))
     39 
     40         return default_endpoints

/opt/conda/lib/python3.5/site-packages/sparkmagic/livyclientlib/endpoint.py in __init__(self, url, auth, username, password, implicitly_added)
      8             raise BadUserDataException(u"URL must not be empty")
      9         if auth not in AUTHS_SUPPORTED:
---> 10             raise BadUserConfigurationException(u"Auth '{}' not supported".format(auth))
     11 
     12         self.url = url.rstrip(u"/")

BadUserConfigurationException: Auth 'None' not supported
```

Should it not work locally without authentication? My config.json is as in the previous post: It has no passwords or usernames.

**Comment by aggFTW** [comment] 2017-07-19 18:27
Cool. Just so you know, you need to do `git pull jupyter-incubator master` from a clone if you want to merge what's on here to your clone. Don't know what level of expertise you have, but I thought it wouldn't hurt to state here for other to come.

I'll close this issue for now since I didn't get replies from the original poster.

**Closed by aggFTW** 2017-07-19 18:27 UTC

**Comment by tylerxXx** [comment] 2019-05-22 10:35
I'm having a similar issue that getting "Error sending http request and maximum retry encountered" when I run any code on any kernels.

I have the latest version 0.12.7, and copied the sample config.json file. I have jupyter and Spark installed by anaconda, so didn't use Docker.
![error](https://user-images.githubusercontent.com/31493801/58168225-1131db80-7cd1-11e9-9619-e7272f1f5303.jpg)

**Comment by ghoshkunal123** [comment] 2019-09-06 16:04
I have had the same issue from Jupyter Notebook from SageMaker, just by restarting the kernal the problem went away.

**Comment by surbhijain-zomato** [comment] 2019-12-02 08:19
> I'm having a similar issue that getting "Error sending http request and maximum retry encountered" when I run any code on any kernels.
> 
> I have the latest version 0.12.7, and copied the sample config.json file. I have jupyter and Spark installed by anaconda, so didn't use Docker.
> ![error](https://user-images.githubusercontent.com/31493801/58168225-1131db80-7cd1-11e9-9619-e7272f1f5303.jpg)

I am facing the same issue. Any solution to this?

**Comment by wtfzambo** [comment] 2020-01-09 14:53
Same shit here as @surbhijain-zomato.

It was working a couple weeks ago, now for some reason it gives me this bug, and nothing changed.

**Comment by Data-Jack** [comment] 2021-07-28 14:52
> I'm having a similar issue that getting "Error sending http request and maximum retry encountered" when I run any code on any kernels.
> 
> I have the latest version 0.12.7, and copied the sample config.json file. I have jupyter and Spark installed by anaconda, so didn't use Docker.
> ![error](https://user-images.githubusercontent.com/31493801/58168225-1131db80-7cd1-11e9-9619-e7272f1f5303.jpg)

@surbhijain-zomato, @tylerxiety 

I experienced this same problem from within sagemaker studio. I did the below and if fixed the problem for me but has anyone found a solution that does not involve manually editing a config file?? It's really annoying to do.

From  ~/.sparkmagic/logs found that it was trying to connect with address "http://ip-10-0-0-113.ec2.internal:8998/sessions".

`2021-07-28 14:00:30,129 ERROR   ReliableHttpClient      Request to 'http://ip-10-0-0-113.ec2.internal:8998/sessions' failed with 'HTTPConnectionPool(host='ip-10-0-0-113.ec2.internal', port=8998): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10145d6350>: Failed to establish a new connection: [Errno -2] Name or service not known'))'`

In a terminal session within the image i installed nano and edited /etc/sparkmagic/config.jso to contain url "http://10.0.0.113:8998" ( see below)  and now it works for me.
```
  "kernel_python_credentials": {
    "username": "Livy",
    "password": "",
    "url": "http://10.0.0.113:8998",
    "auth": "None"
  },
```
