### ISSUE TITLE
[BUG]required field "type_ignores" missing from Module

### ISSUE THREAD

**Issue by hsz1273327** [jupyter-incubator/sparkmagic#746] opened 2022-01-24 07:09 UTC
**Describe the bug**

![截屏2022-01-24 下午3 08 03](https://user-images.githubusercontent.com/7850148/150737399-c697c159-dc29-4894-8aa8-98e60814a61a.png)

**Versions:**
 - SparkMagic 0.19.1 & 0.18.0
 - Spark 2.3.1

**Comment by devstein** [comment] 2023-01-01 15:49
Duplicate of https://github.com/jupyter-incubator/sparkmagic/issues/748

**Closed by devstein** 2023-01-01 15:49 UTC
