### ISSUE TITLE
Input parameters to %%spark from local.

### ISSUE THREAD

**Issue by lambmeh** [jupyter-incubator/sparkmagic#332] opened 2017-02-20 06:48 UTC
Hi all, sorry for the novice question. I understand that %%spark actually points to a separate kernel on the livy gateway server. How would one pass input parameters from another cell that is %local to %%spark.

**Comment by aggFTW** [comment] 2017-02-21 19:15
Hey, what kind of parameters do you want to pass? What's the use case? As of now, that functionality does not exist.

**Comment by aggFTW** [comment] 2017-03-02 23:00
Closing for now. Please let us know if you have further questions.

**Closed by aggFTW** 2017-03-02 23:00 UTC

**Comment by edoardovivo** [comment] 2017-03-28 11:21
Hello,
I am experiencing the same issue and I fail to see how #327 addresses it. 

The problem is quite simple: I am working using a pyspark kernel connected to a Azure HdInsight instance of Spark 2.0 through Livy. 
I have a local file (say, a csv) that I need to read and then use as a remote spark dataframe (i.e. a dataframe living in my cluster in the cloud) in combination with some other remote dataframes. 

What I CAN do is the other way around, i.e. using %%sql -o in combination with %%local in order to plot data from the remote dataframe, but that is not what I want. 

Could you please suggest any way in which I can accomplish this task? It would be much appreciated.
Thank you again

**Comment by aggFTW** [comment] 2017-03-28 17:43
@edoardovivo 
#327 doesn't address it. It only allows you to go from a spark dataframe directly to a local pandas variable.

You cannot read locally from a csv in your computer and send it to the remote spark cluster. If you want to read a csv file, the file must be in the cluster storage. In the case of HDInsight, that will be either the container for the cluster in your Azure Storage account or in ADLS.

**Comment by wkupersa** [comment] 2017-06-09 17:11
Sorry to comment on a closed issue but have similar need / differernt use case.  I am trying to use getpass in my notebook and then pass the creds through the livy session so that I can authenticate to Splunk to do data retrieval into spark.

**Comment by aggFTW** [comment] 2017-06-14 18:30
That scenario is not supported yet. There's no ETA for it. We welcome PRs.

**Comment by absenceispresence** [comment] 2017-10-05 05:52
How about the case where I want to load some data(eg. serialised, trained model from local file) and pass it to `%%spark` kernel?

The only solution I can think of is saving the local file in Hive (in some table with just one string/byte column) and then loading it on `%%spark` kernel as a regular dataframe.

It would be nice to have option to do that without writing such ugly code.

**Comment by aggFTW** [comment] 2017-10-06 17:42
Yes, that is indeed ugly. Your scenario is very similar to what @edoardovivo wanted to do, and alas, we still don't have any way to serialize data from local disk and send it to the remote cluster for spark to be able to access it.

The only way I can think of this feature coming in is via a magic that lets you specify a local file in your file system, read the contents of the file, and sends code to the livy session to save the contents of the file into the default HDFS of the Spark cluster. The user would then be able to access the file from the location specified in HDFS.

This, however, seems like it's better done in some other way, out of band of sparkmagic... hmmm

Thoughts?

**Comment by absenceispresence** [comment] 2017-10-07 19:22
@aggFTW Thanks for the response(and for confirmation that it is indeed not easily achieved - I thought I was missing something fundamental).

It does not necessary have to be a file, a simple dataframe would suffice. How is `%spark -o` implemented? Can't we have the same exact functionality but kind of "reversed" - for sending a premade (pandas or pyspark) dataframe from `%local` cell to spark?

How much time do you think such feature would take to implement? Would the person not-really-knowing-and-using-sparkmagic-too-much be able to do it?

**Comment by aggFTW** [comment] 2017-10-10 19:01
It would probably take 24 hours or so for someone to get everything right with unit tests who knows what they are doing. Probably add 12 hours or so for someone new to the code base?

`-o` is implemented by sending the spark dataframe as JSON and then constructing the JSON into a pandas dataframe locally and putting that dataframe in a variable. We could potentially get the JSON representation of a local pandas dataframe, put it into some spark code that could transform the JSON representation into a spark dataframe, and put that into a variable. It's doable, there's just concerns around escaping the JSON right, handling multiple encodings, limiting the amount of data you can send, letting the user configure that, supporting the different versions of spark, and handling all of these for the multiple languages we support, both in the kernels and in the magic-based ipython kernel scenarios.

Sparkmagic is written in such a way that it's very easy to implement once and use that code in all kernels. If you are comfortable with spark and reading python code, you could try to tackle it, and I could support along the way.

I don't have the cycles atm to implement it.

**Comment by sangramga** [comment] 2019-04-19 09:15
@spaszek @aggFTW Sorry to comment on closed issue, but has anybody started working on it. If yes, could you point me to the PR or Github issue? SInce, I'm facing the same use case..pushing local files/pandas dataframes to remote Spark kernel via Sparkmagic/Livy.
